import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/UI/Navbar";
import BottomNav from "./components/UI/BottomNav";
import Providers from "./providers";
import authenticated from "./auth/authenticated";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isAuthenticated = await authenticated();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers authenticated={isAuthenticated}>
          <Navbar />
          <main className="max-w-screen-xl py-12 px-2 sm:px-4 sm:py-14 lg:px-8 lg:py-24">
            {children}
          </main>
          <BottomNav />
        </Providers>
      </body>
    </html>
  );
}
